### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by superen7527** [XIU2/SNIProxy#9]
### 问题描述

运行一天好好的 第二天就这样了 日志刷了好几分钟才出来 下面全是这个 
```
goroutine 2141496 [chan send]:
main.ioReflector({0x7f7793a1b048?, 0xc0a76f3380}, {0x5c83e0, 0xc0a74d3ec0}, 0x0, 0xc09c2f7620, {0xc06c7e24a0, 0x10}, {0xc06c8ba2b8, 0x11})
        C:/Github/SNIProxy/main.go:230 +0x2b1
created by main.forward
        C:/Github/SNIProxy/main.go:212 +0x325

goroutine 2141497 [chan send]:
main.onDisconnect({0x7f7793a1b048?, 0xc0a74d3ec0?}, 0xc0000a20d0?)
        C:/Github/SNIProxy/main.go:238 +0x3d
main.ioReflector({0x7f7793a1b048?, 0xc0a74d3ec0}, {0x5c83e0, 0xc0a76f3380}, 0x1, 0xc09c2f7620, {0xc06c7e24a0, 0x10}, {0xc06c8ba2b8, 0x11})
        C:/Github/SNIProxy/main.go:231 +0x2c3
created by main.forward
        C:/Github/SNIProxy/main.go:213 +0x44a

goroutine 2141508 [chan send]:
main.onDisconnect({0x7f7793a1b048?, 0xc0a74d3ec8?}, 0xc0001aa410?)
        C:/Github/SNIProxy/main.go:238 +0x3d
main.ioReflector({0x7f7793a1b048?, 0xc0a74d3ec8}, {0x5c83e0, 0xc0a92961f0}, 0x1, 0xc09c604180, {0xc06c7e2510, 0x10}, {0xc06c220db0, 0x11})
        C:/Github/SNIProxy/main.go:231 +0x2c3
created by main.forward
        C:/Github/SNIProxy/main.go:213 +0x44a
```

### 软件版本

最新版

**Comment by XIU2** [comment]
你提高的报错信息是不完整的（缺少了最重要的报错开头部分，也就是具体报错原因），不过大概率是 #4 或 #11 。

另外，系统服务配置文件里我忘记加上用于守护进程的配置项了（`Restart=on-failure`），因此在 SNIProxy 服务异常退出后，没有自动恢复启动，修改下服务配置文件加上这个试试。这样对于一些小概率报错引起的异常退出，也不用担心来不及恢复了。
[# Linux 配置为系统服务 (systemd - 以支持开机启动、守护进程等)](https://github.com/XIU2/SNIProxy#-linux-配置为系统服务-systemd---以支持开机启动守护进程等)
